// Code generated by protoc-gen-go. DO NOT EDIT.
// source: raft.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Log_LogType int32

const (
	Log_LOG_COMMAND                Log_LogType = 0
	Log_LOG_NOOP                   Log_LogType = 1
	Log_LOG_ADD_PEER_DEPRECATED    Log_LogType = 2
	Log_LOG_REMOVE_PEER_DEPRECATED Log_LogType = 3
	Log_LOG_BARRIER                Log_LogType = 4
	Log_LOG_CONFIGURATION          Log_LogType = 5
)

var Log_LogType_name = map[int32]string{
	0: "LOG_COMMAND",
	1: "LOG_NOOP",
	2: "LOG_ADD_PEER_DEPRECATED",
	3: "LOG_REMOVE_PEER_DEPRECATED",
	4: "LOG_BARRIER",
	5: "LOG_CONFIGURATION",
}

var Log_LogType_value = map[string]int32{
	"LOG_COMMAND":                0,
	"LOG_NOOP":                   1,
	"LOG_ADD_PEER_DEPRECATED":    2,
	"LOG_REMOVE_PEER_DEPRECATED": 3,
	"LOG_BARRIER":                4,
	"LOG_CONFIGURATION":          5,
}

func (x Log_LogType) String() string {
	return proto.EnumName(Log_LogType_name, int32(x))
}

func (Log_LogType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{1, 0}
}

type RPCHeader struct {
	ProtocolVersion      int64    `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RPCHeader) Reset()         { *m = RPCHeader{} }
func (m *RPCHeader) String() string { return proto.CompactTextString(m) }
func (*RPCHeader) ProtoMessage()    {}
func (*RPCHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{0}
}

func (m *RPCHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RPCHeader.Unmarshal(m, b)
}
func (m *RPCHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RPCHeader.Marshal(b, m, deterministic)
}
func (m *RPCHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPCHeader.Merge(m, src)
}
func (m *RPCHeader) XXX_Size() int {
	return xxx_messageInfo_RPCHeader.Size(m)
}
func (m *RPCHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_RPCHeader.DiscardUnknown(m)
}

var xxx_messageInfo_RPCHeader proto.InternalMessageInfo

func (m *RPCHeader) GetProtocolVersion() int64 {
	if m != nil {
		return m.ProtocolVersion
	}
	return 0
}

type Log struct {
	Index                uint64      `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Term                 uint64      `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	Type                 Log_LogType `protobuf:"varint,3,opt,name=type,proto3,enum=Log_LogType" json:"type,omitempty"`
	Data                 []byte      `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Extensions           []byte      `protobuf:"bytes,5,opt,name=extensions,proto3" json:"extensions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Log) Reset()         { *m = Log{} }
func (m *Log) String() string { return proto.CompactTextString(m) }
func (*Log) ProtoMessage()    {}
func (*Log) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{1}
}

func (m *Log) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Log.Unmarshal(m, b)
}
func (m *Log) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Log.Marshal(b, m, deterministic)
}
func (m *Log) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Log.Merge(m, src)
}
func (m *Log) XXX_Size() int {
	return xxx_messageInfo_Log.Size(m)
}
func (m *Log) XXX_DiscardUnknown() {
	xxx_messageInfo_Log.DiscardUnknown(m)
}

var xxx_messageInfo_Log proto.InternalMessageInfo

func (m *Log) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Log) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *Log) GetType() Log_LogType {
	if m != nil {
		return m.Type
	}
	return Log_LOG_COMMAND
}

func (m *Log) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Log) GetExtensions() []byte {
	if m != nil {
		return m.Extensions
	}
	return nil
}

type AppendEntriesRequest struct {
	RpcHeader            *RPCHeader `protobuf:"bytes,1,opt,name=rpc_header,json=rpcHeader,proto3" json:"rpc_header,omitempty"`
	Term                 uint64     `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	Leader               []byte     `protobuf:"bytes,3,opt,name=leader,proto3" json:"leader,omitempty"`
	PrevLogEntry         uint64     `protobuf:"varint,4,opt,name=prev_log_entry,json=prevLogEntry,proto3" json:"prev_log_entry,omitempty"`
	PrevLogTerm          uint64     `protobuf:"varint,5,opt,name=prev_log_term,json=prevLogTerm,proto3" json:"prev_log_term,omitempty"`
	Entries              []*Log     `protobuf:"bytes,6,rep,name=entries,proto3" json:"entries,omitempty"`
	LeaderCommitIndex    uint64     `protobuf:"varint,7,opt,name=leader_commit_index,json=leaderCommitIndex,proto3" json:"leader_commit_index,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AppendEntriesRequest) Reset()         { *m = AppendEntriesRequest{} }
func (m *AppendEntriesRequest) String() string { return proto.CompactTextString(m) }
func (*AppendEntriesRequest) ProtoMessage()    {}
func (*AppendEntriesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{2}
}

func (m *AppendEntriesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendEntriesRequest.Unmarshal(m, b)
}
func (m *AppendEntriesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendEntriesRequest.Marshal(b, m, deterministic)
}
func (m *AppendEntriesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendEntriesRequest.Merge(m, src)
}
func (m *AppendEntriesRequest) XXX_Size() int {
	return xxx_messageInfo_AppendEntriesRequest.Size(m)
}
func (m *AppendEntriesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendEntriesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AppendEntriesRequest proto.InternalMessageInfo

func (m *AppendEntriesRequest) GetRpcHeader() *RPCHeader {
	if m != nil {
		return m.RpcHeader
	}
	return nil
}

func (m *AppendEntriesRequest) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntriesRequest) GetLeader() []byte {
	if m != nil {
		return m.Leader
	}
	return nil
}

func (m *AppendEntriesRequest) GetPrevLogEntry() uint64 {
	if m != nil {
		return m.PrevLogEntry
	}
	return 0
}

func (m *AppendEntriesRequest) GetPrevLogTerm() uint64 {
	if m != nil {
		return m.PrevLogTerm
	}
	return 0
}

func (m *AppendEntriesRequest) GetEntries() []*Log {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *AppendEntriesRequest) GetLeaderCommitIndex() uint64 {
	if m != nil {
		return m.LeaderCommitIndex
	}
	return 0
}

type AppendEntriesResponse struct {
	RpcHeader            *RPCHeader `protobuf:"bytes,1,opt,name=rpc_header,json=rpcHeader,proto3" json:"rpc_header,omitempty"`
	Term                 uint64     `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	LastLog              uint64     `protobuf:"varint,3,opt,name=last_log,json=lastLog,proto3" json:"last_log,omitempty"`
	Success              bool       `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	NoRetryBackoff       bool       `protobuf:"varint,5,opt,name=no_retry_backoff,json=noRetryBackoff,proto3" json:"no_retry_backoff,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AppendEntriesResponse) Reset()         { *m = AppendEntriesResponse{} }
func (m *AppendEntriesResponse) String() string { return proto.CompactTextString(m) }
func (*AppendEntriesResponse) ProtoMessage()    {}
func (*AppendEntriesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{3}
}

func (m *AppendEntriesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendEntriesResponse.Unmarshal(m, b)
}
func (m *AppendEntriesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendEntriesResponse.Marshal(b, m, deterministic)
}
func (m *AppendEntriesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendEntriesResponse.Merge(m, src)
}
func (m *AppendEntriesResponse) XXX_Size() int {
	return xxx_messageInfo_AppendEntriesResponse.Size(m)
}
func (m *AppendEntriesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendEntriesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AppendEntriesResponse proto.InternalMessageInfo

func (m *AppendEntriesResponse) GetRpcHeader() *RPCHeader {
	if m != nil {
		return m.RpcHeader
	}
	return nil
}

func (m *AppendEntriesResponse) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntriesResponse) GetLastLog() uint64 {
	if m != nil {
		return m.LastLog
	}
	return 0
}

func (m *AppendEntriesResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *AppendEntriesResponse) GetNoRetryBackoff() bool {
	if m != nil {
		return m.NoRetryBackoff
	}
	return false
}

type RequestVoteRequest struct {
	RpcHeader            *RPCHeader `protobuf:"bytes,1,opt,name=rpc_header,json=rpcHeader,proto3" json:"rpc_header,omitempty"`
	Term                 uint64     `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	Candidate            []byte     `protobuf:"bytes,3,opt,name=candidate,proto3" json:"candidate,omitempty"`
	LastLogIndex         uint64     `protobuf:"varint,4,opt,name=last_log_index,json=lastLogIndex,proto3" json:"last_log_index,omitempty"`
	LastLogTerm          uint64     `protobuf:"varint,5,opt,name=last_log_term,json=lastLogTerm,proto3" json:"last_log_term,omitempty"`
	LeadershipTransfer   bool       `protobuf:"varint,6,opt,name=leadership_transfer,json=leadershipTransfer,proto3" json:"leadership_transfer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RequestVoteRequest) Reset()         { *m = RequestVoteRequest{} }
func (m *RequestVoteRequest) String() string { return proto.CompactTextString(m) }
func (*RequestVoteRequest) ProtoMessage()    {}
func (*RequestVoteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{4}
}

func (m *RequestVoteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestVoteRequest.Unmarshal(m, b)
}
func (m *RequestVoteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestVoteRequest.Marshal(b, m, deterministic)
}
func (m *RequestVoteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestVoteRequest.Merge(m, src)
}
func (m *RequestVoteRequest) XXX_Size() int {
	return xxx_messageInfo_RequestVoteRequest.Size(m)
}
func (m *RequestVoteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestVoteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RequestVoteRequest proto.InternalMessageInfo

func (m *RequestVoteRequest) GetRpcHeader() *RPCHeader {
	if m != nil {
		return m.RpcHeader
	}
	return nil
}

func (m *RequestVoteRequest) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *RequestVoteRequest) GetCandidate() []byte {
	if m != nil {
		return m.Candidate
	}
	return nil
}

func (m *RequestVoteRequest) GetLastLogIndex() uint64 {
	if m != nil {
		return m.LastLogIndex
	}
	return 0
}

func (m *RequestVoteRequest) GetLastLogTerm() uint64 {
	if m != nil {
		return m.LastLogTerm
	}
	return 0
}

func (m *RequestVoteRequest) GetLeadershipTransfer() bool {
	if m != nil {
		return m.LeadershipTransfer
	}
	return false
}

type RequestVoteResponse struct {
	RpcHeader            *RPCHeader `protobuf:"bytes,1,opt,name=rpc_header,json=rpcHeader,proto3" json:"rpc_header,omitempty"`
	Term                 uint64     `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	Peers                []byte     `protobuf:"bytes,3,opt,name=peers,proto3" json:"peers,omitempty"`
	Granted              bool       `protobuf:"varint,4,opt,name=granted,proto3" json:"granted,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RequestVoteResponse) Reset()         { *m = RequestVoteResponse{} }
func (m *RequestVoteResponse) String() string { return proto.CompactTextString(m) }
func (*RequestVoteResponse) ProtoMessage()    {}
func (*RequestVoteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{5}
}

func (m *RequestVoteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestVoteResponse.Unmarshal(m, b)
}
func (m *RequestVoteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestVoteResponse.Marshal(b, m, deterministic)
}
func (m *RequestVoteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestVoteResponse.Merge(m, src)
}
func (m *RequestVoteResponse) XXX_Size() int {
	return xxx_messageInfo_RequestVoteResponse.Size(m)
}
func (m *RequestVoteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestVoteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RequestVoteResponse proto.InternalMessageInfo

func (m *RequestVoteResponse) GetRpcHeader() *RPCHeader {
	if m != nil {
		return m.RpcHeader
	}
	return nil
}

func (m *RequestVoteResponse) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *RequestVoteResponse) GetPeers() []byte {
	if m != nil {
		return m.Peers
	}
	return nil
}

func (m *RequestVoteResponse) GetGranted() bool {
	if m != nil {
		return m.Granted
	}
	return false
}

type TimeoutNowRequest struct {
	RpcHeader            *RPCHeader `protobuf:"bytes,1,opt,name=rpc_header,json=rpcHeader,proto3" json:"rpc_header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *TimeoutNowRequest) Reset()         { *m = TimeoutNowRequest{} }
func (m *TimeoutNowRequest) String() string { return proto.CompactTextString(m) }
func (*TimeoutNowRequest) ProtoMessage()    {}
func (*TimeoutNowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{6}
}

func (m *TimeoutNowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeoutNowRequest.Unmarshal(m, b)
}
func (m *TimeoutNowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeoutNowRequest.Marshal(b, m, deterministic)
}
func (m *TimeoutNowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeoutNowRequest.Merge(m, src)
}
func (m *TimeoutNowRequest) XXX_Size() int {
	return xxx_messageInfo_TimeoutNowRequest.Size(m)
}
func (m *TimeoutNowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeoutNowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TimeoutNowRequest proto.InternalMessageInfo

func (m *TimeoutNowRequest) GetRpcHeader() *RPCHeader {
	if m != nil {
		return m.RpcHeader
	}
	return nil
}

type TimeoutNowResponse struct {
	RpcHeader            *RPCHeader `protobuf:"bytes,1,opt,name=rpc_header,json=rpcHeader,proto3" json:"rpc_header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *TimeoutNowResponse) Reset()         { *m = TimeoutNowResponse{} }
func (m *TimeoutNowResponse) String() string { return proto.CompactTextString(m) }
func (*TimeoutNowResponse) ProtoMessage()    {}
func (*TimeoutNowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{7}
}

func (m *TimeoutNowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeoutNowResponse.Unmarshal(m, b)
}
func (m *TimeoutNowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeoutNowResponse.Marshal(b, m, deterministic)
}
func (m *TimeoutNowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeoutNowResponse.Merge(m, src)
}
func (m *TimeoutNowResponse) XXX_Size() int {
	return xxx_messageInfo_TimeoutNowResponse.Size(m)
}
func (m *TimeoutNowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeoutNowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TimeoutNowResponse proto.InternalMessageInfo

func (m *TimeoutNowResponse) GetRpcHeader() *RPCHeader {
	if m != nil {
		return m.RpcHeader
	}
	return nil
}

// The first InstallSnapshotRequest on the stream contains all the metadata.
// All further messages contain only data.
type InstallSnapshotRequest struct {
	RpcHeader            *RPCHeader `protobuf:"bytes,1,opt,name=rpc_header,json=rpcHeader,proto3" json:"rpc_header,omitempty"`
	Term                 uint64     `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	Leader               []byte     `protobuf:"bytes,3,opt,name=leader,proto3" json:"leader,omitempty"`
	LastLogIndex         uint64     `protobuf:"varint,4,opt,name=last_log_index,json=lastLogIndex,proto3" json:"last_log_index,omitempty"`
	LastLogTerm          uint64     `protobuf:"varint,5,opt,name=last_log_term,json=lastLogTerm,proto3" json:"last_log_term,omitempty"`
	Peers                []byte     `protobuf:"bytes,6,opt,name=peers,proto3" json:"peers,omitempty"`
	Configuration        []byte     `protobuf:"bytes,7,opt,name=configuration,proto3" json:"configuration,omitempty"`
	ConfigurationIndex   uint64     `protobuf:"varint,8,opt,name=configuration_index,json=configurationIndex,proto3" json:"configuration_index,omitempty"`
	Size                 int64      `protobuf:"varint,9,opt,name=size,proto3" json:"size,omitempty"`
	Data                 []byte     `protobuf:"bytes,10,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *InstallSnapshotRequest) Reset()         { *m = InstallSnapshotRequest{} }
func (m *InstallSnapshotRequest) String() string { return proto.CompactTextString(m) }
func (*InstallSnapshotRequest) ProtoMessage()    {}
func (*InstallSnapshotRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{8}
}

func (m *InstallSnapshotRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstallSnapshotRequest.Unmarshal(m, b)
}
func (m *InstallSnapshotRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstallSnapshotRequest.Marshal(b, m, deterministic)
}
func (m *InstallSnapshotRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstallSnapshotRequest.Merge(m, src)
}
func (m *InstallSnapshotRequest) XXX_Size() int {
	return xxx_messageInfo_InstallSnapshotRequest.Size(m)
}
func (m *InstallSnapshotRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InstallSnapshotRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InstallSnapshotRequest proto.InternalMessageInfo

func (m *InstallSnapshotRequest) GetRpcHeader() *RPCHeader {
	if m != nil {
		return m.RpcHeader
	}
	return nil
}

func (m *InstallSnapshotRequest) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *InstallSnapshotRequest) GetLeader() []byte {
	if m != nil {
		return m.Leader
	}
	return nil
}

func (m *InstallSnapshotRequest) GetLastLogIndex() uint64 {
	if m != nil {
		return m.LastLogIndex
	}
	return 0
}

func (m *InstallSnapshotRequest) GetLastLogTerm() uint64 {
	if m != nil {
		return m.LastLogTerm
	}
	return 0
}

func (m *InstallSnapshotRequest) GetPeers() []byte {
	if m != nil {
		return m.Peers
	}
	return nil
}

func (m *InstallSnapshotRequest) GetConfiguration() []byte {
	if m != nil {
		return m.Configuration
	}
	return nil
}

func (m *InstallSnapshotRequest) GetConfigurationIndex() uint64 {
	if m != nil {
		return m.ConfigurationIndex
	}
	return 0
}

func (m *InstallSnapshotRequest) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *InstallSnapshotRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type InstallSnapshotResponse struct {
	RpcHeader            *RPCHeader `protobuf:"bytes,1,opt,name=rpc_header,json=rpcHeader,proto3" json:"rpc_header,omitempty"`
	Term                 uint64     `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	Success              bool       `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *InstallSnapshotResponse) Reset()         { *m = InstallSnapshotResponse{} }
func (m *InstallSnapshotResponse) String() string { return proto.CompactTextString(m) }
func (*InstallSnapshotResponse) ProtoMessage()    {}
func (*InstallSnapshotResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{9}
}

func (m *InstallSnapshotResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstallSnapshotResponse.Unmarshal(m, b)
}
func (m *InstallSnapshotResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstallSnapshotResponse.Marshal(b, m, deterministic)
}
func (m *InstallSnapshotResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstallSnapshotResponse.Merge(m, src)
}
func (m *InstallSnapshotResponse) XXX_Size() int {
	return xxx_messageInfo_InstallSnapshotResponse.Size(m)
}
func (m *InstallSnapshotResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InstallSnapshotResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InstallSnapshotResponse proto.InternalMessageInfo

func (m *InstallSnapshotResponse) GetRpcHeader() *RPCHeader {
	if m != nil {
		return m.RpcHeader
	}
	return nil
}

func (m *InstallSnapshotResponse) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *InstallSnapshotResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterEnum("Log_LogType", Log_LogType_name, Log_LogType_value)
	proto.RegisterType((*RPCHeader)(nil), "RPCHeader")
	proto.RegisterType((*Log)(nil), "Log")
	proto.RegisterType((*AppendEntriesRequest)(nil), "AppendEntriesRequest")
	proto.RegisterType((*AppendEntriesResponse)(nil), "AppendEntriesResponse")
	proto.RegisterType((*RequestVoteRequest)(nil), "RequestVoteRequest")
	proto.RegisterType((*RequestVoteResponse)(nil), "RequestVoteResponse")
	proto.RegisterType((*TimeoutNowRequest)(nil), "TimeoutNowRequest")
	proto.RegisterType((*TimeoutNowResponse)(nil), "TimeoutNowResponse")
	proto.RegisterType((*InstallSnapshotRequest)(nil), "InstallSnapshotRequest")
	proto.RegisterType((*InstallSnapshotResponse)(nil), "InstallSnapshotResponse")
}

func init() { proto.RegisterFile("raft.proto", fileDescriptor_b042552c306ae59b) }

var fileDescriptor_b042552c306ae59b = []byte{
	// 846 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xcd, 0x6e, 0xeb, 0x44,
	0x14, 0xae, 0x13, 0xe7, 0xa7, 0x27, 0xfd, 0x49, 0xa7, 0x7f, 0x26, 0xa0, 0x2a, 0xb2, 0xae, 0x50,
	0xee, 0xc6, 0x85, 0x22, 0x81, 0x60, 0x01, 0xa4, 0x8d, 0xb9, 0x37, 0x52, 0x9a, 0x44, 0x73, 0x43,
	0x17, 0x6c, 0x2c, 0xd7, 0x99, 0x38, 0x16, 0xce, 0x8c, 0x99, 0x99, 0xdc, 0x7b, 0xc3, 0x1a, 0x89,
	0x15, 0x4b, 0x1e, 0x85, 0xd7, 0x60, 0xc7, 0x5b, 0xf0, 0x10, 0x68, 0xc6, 0x76, 0x9a, 0x34, 0x61,
	0x51, 0x51, 0x16, 0x55, 0x7d, 0xbe, 0x6f, 0x3c, 0x33, 0xe7, 0xfb, 0xce, 0x39, 0x31, 0x00, 0xf7,
	0x27, 0xd2, 0x49, 0x38, 0x93, 0xcc, 0xfe, 0x1c, 0x76, 0xf1, 0xf0, 0xe6, 0x35, 0xf1, 0xc7, 0x84,
	0xa3, 0x97, 0x50, 0xd7, 0x68, 0xc0, 0x62, 0xef, 0x2d, 0xe1, 0x22, 0x62, 0xd4, 0x32, 0x9a, 0x46,
	0xab, 0x88, 0x0f, 0x73, 0xfc, 0x2e, 0x85, 0xed, 0xdf, 0x0b, 0x50, 0xec, 0xb1, 0x10, 0x9d, 0x40,
	0x29, 0xa2, 0x63, 0xf2, 0x5e, 0xaf, 0x33, 0x71, 0x1a, 0x20, 0x04, 0xa6, 0x24, 0x7c, 0x66, 0x15,
	0x34, 0xa8, 0x9f, 0x51, 0x13, 0x4c, 0xb9, 0x48, 0x88, 0x55, 0x6c, 0x1a, 0xad, 0x83, 0xab, 0x3d,
	0xa7, 0xc7, 0x42, 0xf5, 0x37, 0x5a, 0x24, 0x04, 0x6b, 0x46, 0xbd, 0x35, 0xf6, 0xa5, 0x6f, 0x99,
	0x4d, 0xa3, 0xb5, 0x87, 0xf5, 0x33, 0xba, 0x00, 0x20, 0xef, 0x25, 0xa1, 0xea, 0x50, 0x61, 0x95,
	0x34, 0xb3, 0x82, 0xd8, 0xbf, 0x19, 0x50, 0xc9, 0x76, 0x41, 0x87, 0x50, 0xeb, 0x0d, 0x5e, 0x79,
	0x37, 0x83, 0xdb, 0xdb, 0x76, 0xbf, 0x53, 0xdf, 0x41, 0x7b, 0x50, 0x55, 0x40, 0x7f, 0x30, 0x18,
	0xd6, 0x0d, 0xf4, 0x21, 0x9c, 0xab, 0xa8, 0xdd, 0xe9, 0x78, 0x43, 0xd7, 0xc5, 0x5e, 0xc7, 0x1d,
	0x62, 0xf7, 0xa6, 0x3d, 0x72, 0x3b, 0xf5, 0x02, 0xba, 0x80, 0x86, 0x22, 0xb1, 0x7b, 0x3b, 0xb8,
	0x73, 0x37, 0xf8, 0x62, 0xbe, 0xf7, 0x75, 0x1b, 0xe3, 0xae, 0x8b, 0xeb, 0x26, 0x3a, 0x85, 0xa3,
	0xf4, 0xb0, 0xfe, 0x77, 0xdd, 0x57, 0xdf, 0xe3, 0xf6, 0xa8, 0x3b, 0xe8, 0xd7, 0x4b, 0xf6, 0xaf,
	0x05, 0x38, 0x69, 0x27, 0x09, 0xa1, 0x63, 0x97, 0x4a, 0x1e, 0x11, 0x81, 0xc9, 0x4f, 0x73, 0x22,
	0x24, 0x7a, 0x09, 0xc0, 0x93, 0xc0, 0x9b, 0x6a, 0xa5, 0xb5, 0x5a, 0xb5, 0x2b, 0x70, 0x96, 0xda,
	0xe3, 0x5d, 0x9e, 0x04, 0x99, 0x0d, 0xdb, 0xd4, 0x3b, 0x83, 0x72, 0x9c, 0xbe, 0x5a, 0xd4, 0x1a,
	0x64, 0x11, 0x7a, 0x01, 0x07, 0x09, 0x27, 0x6f, 0xbd, 0x98, 0x85, 0x1e, 0xa1, 0x92, 0x2f, 0xb4,
	0x7a, 0x26, 0xde, 0x53, 0x68, 0x8f, 0x85, 0xea, 0x16, 0x0b, 0x64, 0xc3, 0xfe, 0x72, 0x95, 0xde,
	0xba, 0xa4, 0x17, 0xd5, 0xb2, 0x45, 0x23, 0x75, 0xc2, 0x05, 0x54, 0x48, 0x7a, 0x65, 0xab, 0xdc,
	0x2c, 0xb6, 0x6a, 0x57, 0xa6, 0xb2, 0x07, 0xe7, 0x20, 0x72, 0xe0, 0x38, 0x3d, 0xd3, 0x0b, 0xd8,
	0x6c, 0x16, 0x49, 0x2f, 0xf5, 0xbd, 0xa2, 0x77, 0x3a, 0x4a, 0xa9, 0x1b, 0xcd, 0x74, 0x15, 0x61,
	0xff, 0x61, 0xc0, 0xe9, 0x23, 0x25, 0x44, 0xc2, 0xa8, 0x20, 0xff, 0x55, 0x8a, 0x0f, 0xa0, 0x1a,
	0xfb, 0x42, 0xaa, 0x64, 0xb4, 0x18, 0x26, 0xae, 0xa8, 0x58, 0x55, 0xa3, 0x05, 0x15, 0x31, 0x0f,
	0x02, 0x22, 0x84, 0x96, 0xa1, 0x8a, 0xf3, 0x10, 0xb5, 0xa0, 0x4e, 0x99, 0xc7, 0x89, 0xe4, 0x0b,
	0xef, 0xde, 0x0f, 0x7e, 0x64, 0x93, 0x89, 0x16, 0xa1, 0x8a, 0x0f, 0x28, 0xc3, 0x0a, 0xbe, 0x4e,
	0x51, 0xfb, 0x6f, 0x03, 0x50, 0x66, 0xda, 0x1d, 0x93, 0xe4, 0x99, 0xfc, 0xfb, 0x08, 0x76, 0x03,
	0x9f, 0x8e, 0xa3, 0xb1, 0x2f, 0x49, 0x66, 0xe1, 0x03, 0xa0, 0x5c, 0xcc, 0x53, 0xca, 0x64, 0xcd,
	0x5c, 0xcc, 0x12, 0xd3, 0x8a, 0x2a, 0x17, 0x97, 0xab, 0x56, 0x5d, 0xcc, 0x16, 0x69, 0x17, 0x2f,
	0x73, 0x97, 0xc4, 0x34, 0x4a, 0x3c, 0xc9, 0x7d, 0x2a, 0x26, 0x84, 0x5b, 0x65, 0x9d, 0x2a, 0x7a,
	0xa0, 0x46, 0x19, 0x63, 0xff, 0x62, 0xc0, 0xf1, 0x5a, 0xba, 0xcf, 0x63, 0xd2, 0x09, 0x94, 0x12,
	0x42, 0xb8, 0xc8, 0x72, 0x4d, 0x03, 0xe5, 0x4f, 0xc8, 0x7d, 0x2a, 0xc9, 0x38, 0xf7, 0x27, 0x0b,
	0xed, 0xaf, 0xe1, 0x68, 0x14, 0xcd, 0x08, 0x9b, 0xcb, 0x3e, 0x7b, 0xf7, 0x74, 0xcd, 0xed, 0x6f,
	0x00, 0xad, 0xbe, 0xff, 0xe4, 0x24, 0xec, 0x3f, 0x0b, 0x70, 0xd6, 0xa5, 0x42, 0xfa, 0x71, 0xfc,
	0x86, 0xfa, 0x89, 0x98, 0x32, 0xf9, 0xff, 0xb7, 0xee, 0x33, 0x99, 0xbe, 0x14, 0xbb, 0xbc, 0x2a,
	0xf6, 0x0b, 0xd8, 0x0f, 0x18, 0x9d, 0x44, 0xe1, 0x9c, 0xfb, 0x52, 0x8d, 0xf2, 0x8a, 0x66, 0xd7,
	0x41, 0x55, 0x30, 0x6b, 0x40, 0x76, 0x95, 0xaa, 0x3e, 0x05, 0xad, 0x51, 0xdd, 0x7c, 0xb6, 0x8b,
	0xe8, 0x67, 0x62, 0xed, 0xea, 0x1f, 0x06, 0xfd, 0xbc, 0x9c, 0xdc, 0xf0, 0x30, 0xb9, 0x6d, 0x0e,
	0xe7, 0x1b, 0x7a, 0x3e, 0x4f, 0x6d, 0xad, 0x74, 0x79, 0x71, 0xad, 0xcb, 0xaf, 0xfe, 0x2a, 0x80,
	0x89, 0xfd, 0x89, 0x44, 0xbd, 0x47, 0xb3, 0x67, 0x18, 0x25, 0x24, 0x8e, 0x28, 0x41, 0xa7, 0xce,
	0xb6, 0xe9, 0xdc, 0x38, 0x73, 0xb6, 0x8e, 0x2a, 0x7b, 0xa7, 0x65, 0x7c, 0x62, 0xa0, 0x6f, 0x61,
	0x7f, 0x8d, 0x7e, 0xf2, 0x2e, 0xe8, 0x2b, 0xa8, 0xad, 0x34, 0x19, 0x3a, 0x76, 0x36, 0x27, 0x4c,
	0xe3, 0xc4, 0xd9, 0xd2, 0x87, 0xf6, 0x0e, 0xfa, 0x02, 0xe0, 0xa1, 0xb4, 0x11, 0x72, 0x36, 0xfa,
	0xa4, 0x71, 0xec, 0x6c, 0xd6, 0xbe, 0xbd, 0x83, 0x5e, 0xc3, 0xe1, 0x23, 0x07, 0xd0, 0xb9, 0xb3,
	0xbd, 0xc6, 0x1b, 0x96, 0xf3, 0x2f, 0x66, 0x29, 0x09, 0xae, 0x5b, 0x3f, 0x7c, 0x1c, 0x46, 0x72,
	0x3a, 0xbf, 0x77, 0x02, 0x36, 0xbb, 0x6c, 0xc7, 0x31, 0xa1, 0x6f, 0xa6, 0xfe, 0xbb, 0x4f, 0xbf,
	0xbc, 0x54, 0x9f, 0x12, 0x5e, 0xc8, 0x93, 0xe0, 0x52, 0x7f, 0x21, 0xdc, 0x97, 0xf5, 0xbf, 0xcf,
	0xfe, 0x09, 0x00, 0x00, 0xff, 0xff, 0xa4, 0x8b, 0x7c, 0x93, 0x64, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RaftClient is the client API for Raft service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RaftClient interface {
	AppendEntriesPipeline(ctx context.Context, opts ...grpc.CallOption) (Raft_AppendEntriesPipelineClient, error)
	AppendEntries(ctx context.Context, in *AppendEntriesRequest, opts ...grpc.CallOption) (*AppendEntriesResponse, error)
	RequestVote(ctx context.Context, in *RequestVoteRequest, opts ...grpc.CallOption) (*RequestVoteResponse, error)
	TimeoutNow(ctx context.Context, in *TimeoutNowRequest, opts ...grpc.CallOption) (*TimeoutNowResponse, error)
	InstallSnapshot(ctx context.Context, opts ...grpc.CallOption) (Raft_InstallSnapshotClient, error)
}

type raftClient struct {
	cc *grpc.ClientConn
}

func NewRaftClient(cc *grpc.ClientConn) RaftClient {
	return &raftClient{cc}
}

func (c *raftClient) AppendEntriesPipeline(ctx context.Context, opts ...grpc.CallOption) (Raft_AppendEntriesPipelineClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Raft_serviceDesc.Streams[0], "/Raft/AppendEntriesPipeline", opts...)
	if err != nil {
		return nil, err
	}
	x := &raftAppendEntriesPipelineClient{stream}
	return x, nil
}

type Raft_AppendEntriesPipelineClient interface {
	Send(*AppendEntriesRequest) error
	Recv() (*AppendEntriesResponse, error)
	grpc.ClientStream
}

type raftAppendEntriesPipelineClient struct {
	grpc.ClientStream
}

func (x *raftAppendEntriesPipelineClient) Send(m *AppendEntriesRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *raftAppendEntriesPipelineClient) Recv() (*AppendEntriesResponse, error) {
	m := new(AppendEntriesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *raftClient) AppendEntries(ctx context.Context, in *AppendEntriesRequest, opts ...grpc.CallOption) (*AppendEntriesResponse, error) {
	out := new(AppendEntriesResponse)
	err := c.cc.Invoke(ctx, "/Raft/AppendEntries", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftClient) RequestVote(ctx context.Context, in *RequestVoteRequest, opts ...grpc.CallOption) (*RequestVoteResponse, error) {
	out := new(RequestVoteResponse)
	err := c.cc.Invoke(ctx, "/Raft/RequestVote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftClient) TimeoutNow(ctx context.Context, in *TimeoutNowRequest, opts ...grpc.CallOption) (*TimeoutNowResponse, error) {
	out := new(TimeoutNowResponse)
	err := c.cc.Invoke(ctx, "/Raft/TimeoutNow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftClient) InstallSnapshot(ctx context.Context, opts ...grpc.CallOption) (Raft_InstallSnapshotClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Raft_serviceDesc.Streams[1], "/Raft/InstallSnapshot", opts...)
	if err != nil {
		return nil, err
	}
	x := &raftInstallSnapshotClient{stream}
	return x, nil
}

type Raft_InstallSnapshotClient interface {
	Send(*InstallSnapshotRequest) error
	CloseAndRecv() (*InstallSnapshotResponse, error)
	grpc.ClientStream
}

type raftInstallSnapshotClient struct {
	grpc.ClientStream
}

func (x *raftInstallSnapshotClient) Send(m *InstallSnapshotRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *raftInstallSnapshotClient) CloseAndRecv() (*InstallSnapshotResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(InstallSnapshotResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RaftServer is the server API for Raft service.
type RaftServer interface {
	AppendEntriesPipeline(Raft_AppendEntriesPipelineServer) error
	AppendEntries(context.Context, *AppendEntriesRequest) (*AppendEntriesResponse, error)
	RequestVote(context.Context, *RequestVoteRequest) (*RequestVoteResponse, error)
	TimeoutNow(context.Context, *TimeoutNowRequest) (*TimeoutNowResponse, error)
	InstallSnapshot(Raft_InstallSnapshotServer) error
}

// UnimplementedRaftServer can be embedded to have forward compatible implementations.
type UnimplementedRaftServer struct {
}

func (*UnimplementedRaftServer) AppendEntriesPipeline(srv Raft_AppendEntriesPipelineServer) error {
	return status.Errorf(codes.Unimplemented, "method AppendEntriesPipeline not implemented")
}
func (*UnimplementedRaftServer) AppendEntries(ctx context.Context, req *AppendEntriesRequest) (*AppendEntriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppendEntries not implemented")
}
func (*UnimplementedRaftServer) RequestVote(ctx context.Context, req *RequestVoteRequest) (*RequestVoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestVote not implemented")
}
func (*UnimplementedRaftServer) TimeoutNow(ctx context.Context, req *TimeoutNowRequest) (*TimeoutNowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TimeoutNow not implemented")
}
func (*UnimplementedRaftServer) InstallSnapshot(srv Raft_InstallSnapshotServer) error {
	return status.Errorf(codes.Unimplemented, "method InstallSnapshot not implemented")
}

func RegisterRaftServer(s *grpc.Server, srv RaftServer) {
	s.RegisterService(&_Raft_serviceDesc, srv)
}

func _Raft_AppendEntriesPipeline_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RaftServer).AppendEntriesPipeline(&raftAppendEntriesPipelineServer{stream})
}

type Raft_AppendEntriesPipelineServer interface {
	Send(*AppendEntriesResponse) error
	Recv() (*AppendEntriesRequest, error)
	grpc.ServerStream
}

type raftAppendEntriesPipelineServer struct {
	grpc.ServerStream
}

func (x *raftAppendEntriesPipelineServer) Send(m *AppendEntriesResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *raftAppendEntriesPipelineServer) Recv() (*AppendEntriesRequest, error) {
	m := new(AppendEntriesRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Raft_AppendEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServer).AppendEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Raft/AppendEntries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServer).AppendEntries(ctx, req.(*AppendEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raft_RequestVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestVoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServer).RequestVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Raft/RequestVote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServer).RequestVote(ctx, req.(*RequestVoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raft_TimeoutNow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TimeoutNowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServer).TimeoutNow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Raft/TimeoutNow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServer).TimeoutNow(ctx, req.(*TimeoutNowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raft_InstallSnapshot_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RaftServer).InstallSnapshot(&raftInstallSnapshotServer{stream})
}

type Raft_InstallSnapshotServer interface {
	SendAndClose(*InstallSnapshotResponse) error
	Recv() (*InstallSnapshotRequest, error)
	grpc.ServerStream
}

type raftInstallSnapshotServer struct {
	grpc.ServerStream
}

func (x *raftInstallSnapshotServer) SendAndClose(m *InstallSnapshotResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *raftInstallSnapshotServer) Recv() (*InstallSnapshotRequest, error) {
	m := new(InstallSnapshotRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Raft_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Raft",
	HandlerType: (*RaftServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AppendEntries",
			Handler:    _Raft_AppendEntries_Handler,
		},
		{
			MethodName: "RequestVote",
			Handler:    _Raft_RequestVote_Handler,
		},
		{
			MethodName: "TimeoutNow",
			Handler:    _Raft_TimeoutNow_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AppendEntriesPipeline",
			Handler:       _Raft_AppendEntriesPipeline_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "InstallSnapshot",
			Handler:       _Raft_InstallSnapshot_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "raft.proto",
}
